### ISSUE TITLE
Pagina Storico.

### ISSUE THREAD

**Issue by francescobruschetti** [xeela/ProgWeb#110]
- aggiungere l'id dei vari ordini
- non servono tutti i dettagli dei prodotti, se non specificato. Secondo me basta mettere: nome oggetto, prezzo, quantità acquistata
-aggiungere bottone anomalie oppure una "dropbox" con dentro delle voci pre-selezionate tipo: "prodotto non arrivato"
- "prodotto sbagliato"
- "...."

- aggiornare lo stile

**Comment by caterinab** [comment]
TODO:
- bottone anomalie
