### ISSUE TITLE
Cart non va se non aggiungi prima un prodotto

### ISSUE THREAD

**Issue by francescobruschetti** [xeela/ProgWeb#39]
Se l'utente non seleziona un prodotto dalla index, aggiungendolo al carrello, e va direttamente nel carrello, la var json non ha i valori del db

**Comment by pilotapazzo** [comment]
Questo verrà risolto in uno di due modi: 
1. Un filtro che fa passare da un servlet prima di andare sulla pagina "shopping cart"
2. Una richiesta ajax una volta arrivati alla pagina "shopping cart"
